window:
  title: alacritty

  opacity: 1

  padding:
    x: 20
    y: 20

  dimensions:
    columns: 40
    lines: 10

font:
  normal:
    family: Victor Mono
    style: Italic

  bold:
    family: Victor Mono
    style: Semibold Italic
  
  size: 7

colors:
  primary:
    background: '#121212'
    foreground: '#fafafa'
  cursor:
    text:   CellForeground
    cursor: '#fafafa'
  
  normal:
    black:   '#151515'
    red:     '#f45a00'
    green:   '#86b300'
    yellow:  '#f49800'
    blue:    '#399ee6'
    magenta: '#f07171'
    cyan:    '#55b4d4'
    white:   '#fafafa'

  bright:
    black:   '#151515'
    red:     '#f45a00'
    green:   '#86b300'
    yellow:  '#f49800'
    blue:    '#399ee6'
    magenta: '#f07171'
    cyan:    '#55b4d4'
    white:   '#fafafa'

cursor:
  style: Beam
