window:
  opacity: 1

  padding:
    x: 20
    y: 20

  dimensions:
    columns: 40
    lines: 10

font:
  normal:
    family: cozette
    style: Medium

  bold:
    family: cozette
    style: Bold

size: 600000

colors:
  primary:
    background: '#121212'
    foreground: '#fefefe'
  cursor:
    text:   CellForeground
    cursor: '#fefefe'
  
  bright:
    black:   '#151515'
    red:     '#dd6777'
    green:   '#90ceaa'
    yellow:  '#ecd3a0'
    blue:    '#86aaec'
    magenta: '#c296eb'
    cyan:    '#93cee9'
    white:   '#cbced3'
  normal:
    black:   '#252525'
    red:     '#e26c7c'
    green:   '#95d3af'
    yellow:  '#f1d8a5'
    blue:    '#8baff1'
    magenta: '#c79bf0'
    cyan:    '#98d3ee'
    white:   '#d0d3d8'


cursor:
  style: Beam
